[dev]
  command = "npm run dev --prefix frontend"
  port = 5173
  targetPort = 5173
  functions = "backend"

[build]
  command = "npm run build --prefix frontend"
  publish = "frontend/dist"
  functions = "backend"