[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  functions = "../backend/functions"
  publish = "dist"

[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"